spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-us-west-1.aliyuncs.com
      access-key: TODO
      secret-key: TODO
  application:
    name: seabirdmall-third-party

server:
  port: 30000